---
title: "ADM 2303 - Assignment 1"
author: "Renad Gharz"
output: pdf_document
---

# 1. Online Shopping
The trend of online shopping is increasing significantly. Although the number of people who purchase various products and services online is increasing more than ever  before, this trend is still relatively low among people older than 60. To learn more about this issue, a sample of 250 customers (refer to the Excel file) older than 60 who have bought an item online were selected. The number of hours spent related to online shopping during the past six months was recorded.

## 1.1 Mean, Median, and Mode
>Calculate the mean, median, and mode of the number of hours spent related to online shopping.

## 1.2 Variance and Standard Deviation
>Calculate the variance and standard deviation of the number of hours spent related to online shopping.

## 1.3 Boxplot
>Draw a box plot related to the number of hours spent related to online shopping.

## 1.4 Quartiles and IQR
>Determine the first, second, third quartiles, and interquartile range of the number of hours spent related to online shopping.

## 1.5 Reporting Findings
>Briefly describe what you have learned from the statistics you calculated.

# 2. Speed Limit
An insurance company claims that speed limits inside the city are low, and most drivers drive at speeds that they consider safe. The company believes that the city should set the speed limit at a “New” speed limit of the 85th percentile. They collected a random sample of 400 speeds where the limit is 60 km/hr was recorded. Compute the “New” speed limit that the company suggests.

# 3. CO-OP Salary
A business management student wants to learn more about the difference between co-op salaries related to her field of study. She uses a recent survey regarding the degree and co-op salary of four groups of graduates: (1) Business Administration, (2) Accounting, (3)Finance, and (4) Marketing.

## 3.1 Boxplots Comparison
>Draw box plots to compare the four groups of starting salaries.


## 3.2 Reporting Findings
>Report your findings.


# 4. Car Rental Company
A marketing manager of a car rental company wants to analyze the proportion of customers who are above 20 years old. He took a random sample of 500 customers and found out there were 375 customers above age 20. He knows that the true population proportion of customers above age 20 is 0.68.

## 4.1 Shape of Sampling Distribution
>Describe the shape of the sampling distribution of the proportion of customers who are above age 20.


## 4.2 Mean and Standard Deviation
>Find the mean and standard deviation of $\hat{p}$.


## 4.3 Probability of Sample Proportion
>What is the probability that the sample proportion $\hat{p}$ is within 0.03 of the true proportion of customers who are above age 20?


# 5. Annual Salary
The annual salary of the new graduate students of a business school is normally distributed with a mean of $68,000 and a standard deviation of $4,000.

## 5.1 Probability of Random Event
>What is the probability that a randomly selected student receives more than $70,000?


## 5.2 Probability of Sample Mean
>A random sample of five students is selected. What is the probability that the sample mean is greater than $70,000?


## 5.3 Cumulative Probability of Random Event
>In a random sample of five graduate students, what is the probability that all receives more than $70,000?

